### ISSUE TITLE
After running the service, the memory usage has been increasing. 

### ISSUE THREAD

**Issue by DaiHaoguang3151** [Hyuto/yolov7-node#3]
How to solve the problem of memory occupation

**Comment by DaiHaoguang3151** [comment]
The problem has been resolved.
![1701412949501](https://github.com/Hyuto/yolov7-node/assets/131345009/e91b167e-0fc0-457a-a7db-717e91e288bb)

**Comment by Hyuto** [comment]
Thanks, I update this to master
