### ISSUE TITLE
Memory leak in public/js/detect.js

### ISSUE THREAD

**Issue by Zzs2016** [Hyuto/yolov7-node#5]
In line 37,  declared instance：matPad，but don't clean memory.
Causing serious memory leakage issues.
![image](https://github.com/Hyuto/yolov7-node/assets/24717034/c4c48078-535f-4d93-aa4a-40844e1a0032)

**Comment by Hyuto** [comment]
Hello, I think this is the same issue as #3 

Seem deleting `matPad` will resolve the issue. I already update the code in master on last commit.

**Comment by Hyuto** [comment]
I'm closing this issue
